local xform_t const xforms[] = {
    /*   0 */ {        "", identity,       0, ""},
    /*   1 */ {        "", identity,       0, " "},
    /*   2 */ {       " ", identity,       0, " "},
    /*   3 */ {        "", omitfirst,      1, ""},
    /*   4 */ {        "", uppercasefirst, 0, " "},
    /*   5 */ {        "", identity,       0, " the "},
    /*   6 */ {       " ", identity,       0, ""},
    /*   7 */ {      "s ", identity,       0, " "},
    /*   8 */ {        "", identity,       0, " of "},
    /*   9 */ {        "", uppercasefirst, 0, ""},
    /*  10 */ {        "", identity,       0, " and "},
    /*  11 */ {        "", omitfirst,      2, ""},
    /*  12 */ {        "", omitlast,       1, ""},
    /*  13 */ {      ", ", identity,       0, " "},
    /*  14 */ {        "", identity,       0, ", "},
    /*  15 */ {       " ", uppercasefirst, 0, " "},
    /*  16 */ {        "", identity,       0, " in "},
    /*  17 */ {        "", identity,       0, " to "},
    /*  18 */ {      "e ", identity,       0, " "},
    /*  19 */ {        "", identity,       0, "\""},
    /*  20 */ {        "", identity,       0, "."},
    /*  21 */ {        "", identity,       0, "\"&gt;"},
    /*  22 */ {        "", identity,       0, "\n"},
    /*  23 */ {        "", omitlast,       3, ""},
    /*  24 */ {        "", identity,       0, "]"},
    /*  25 */ {        "", identity,       0, " for "},
    /*  26 */ {        "", omitfirst,      3, ""},
    /*  27 */ {        "", omitlast,       2, ""},
    /*  28 */ {        "", identity,       0, " a "},
    /*  29 */ {        "", identity,       0, " that "},
    /*  30 */ {       " ", uppercasefirst, 0, ""},
    /*  31 */ {        "", identity,       0, ". "},
    /*  32 */ {       ".", identity,       0, ""},
    /*  33 */ {       " ", identity,       0, ", "},
    /*  34 */ {        "", omitfirst,      4, ""},
    /*  35 */ {        "", identity,       0, " with "},
    /*  36 */ {        "", identity,       0, "'"},
    /*  37 */ {        "", identity,       0, " from "},
    /*  38 */ {        "", identity,       0, " by "},
    /*  39 */ {        "", omitfirst,      5, ""},
    /*  40 */ {        "", omitfirst,      6, ""},
    /*  41 */ {   " the ", identity,       0, ""},
    /*  42 */ {        "", omitlast,       4, ""},
    /*  43 */ {        "", identity,       0, ". The "},
    /*  44 */ {        "", uppercaseall,   0, ""},
    /*  45 */ {        "", identity,       0, " on "},
    /*  46 */ {        "", identity,       0, " as "},
    /*  47 */ {        "", identity,       0, " is "},
    /*  48 */ {        "", omitlast,       7, ""},
    /*  49 */ {        "", omitlast,       1, "ing "},
    /*  50 */ {        "", identity,       0, "\n\t"},
    /*  51 */ {        "", identity,       0, ":"},
    /*  52 */ {       " ", identity,       0, ". "},
    /*  53 */ {        "", identity,       0, "ed "},
    /*  54 */ {        "", omitfirst,      9, ""},
    /*  55 */ {        "", omitfirst,      7, ""},
    /*  56 */ {        "", omitlast,       6, ""},
    /*  57 */ {        "", identity,       0, "("},
    /*  58 */ {        "", uppercasefirst, 0, ", "},
    /*  59 */ {        "", omitlast,       8, ""},
    /*  60 */ {        "", identity,       0, " at "},
    /*  61 */ {        "", identity,       0, "ly "},
    /*  62 */ {   " the ", identity,       0, " of "},
    /*  63 */ {        "", omitlast,       5, ""},
    /*  64 */ {        "", omitlast,       9, ""},
    /*  65 */ {       " ", uppercasefirst, 0, ", "},
    /*  66 */ {        "", uppercasefirst, 0, "\""},
    /*  67 */ {       ".", identity,       0, "("},
    /*  68 */ {        "", uppercaseall,   0, " "},
    /*  69 */ {        "", uppercasefirst, 0, "\"&gt;"},
    /*  70 */ {        "", identity,       0, "=\""},
    /*  71 */ {       " ", identity,       0, "."},
    /*  72 */ {   ".com/", identity,       0, ""},
    /*  73 */ {   " the ", identity,       0, " of the "},
    /*  74 */ {        "", uppercasefirst, 0, "'"},
    /*  75 */ {        "", identity,       0, ". This "},
    /*  76 */ {        "", identity,       0, ","},
    /*  77 */ {       ".", identity,       0, " "},
    /*  78 */ {        "", uppercasefirst, 0, "("},
    /*  79 */ {        "", uppercasefirst, 0, "."},
    /*  80 */ {        "", identity,       0, " not "},
    /*  81 */ {       " ", identity,       0, "=\""},
    /*  82 */ {        "", identity,       0, "er "},
    /*  83 */ {       " ", uppercaseall,   0, " "},
    /*  84 */ {        "", identity,       0, "al "},
    /*  85 */ {       " ", uppercaseall,   0, ""},
    /*  86 */ {        "", identity,       0, "='"},
    /*  87 */ {        "", uppercaseall,   0, "\""},
    /*  88 */ {        "", uppercasefirst, 0, ". "},
    /*  89 */ {       " ", identity,       0, "("},
    /*  90 */ {        "", identity,       0, "ful "},
    /*  91 */ {       " ", uppercasefirst, 0, ". "},
    /*  92 */ {        "", identity,       0, "ive "},
    /*  93 */ {        "", identity,       0, "less "},
    /*  94 */ {        "", uppercaseall,   0, "'"},
    /*  95 */ {        "", identity,       0, "est "},
    /*  96 */ {       " ", uppercasefirst, 0, "."},
    /*  97 */ {        "", uppercaseall,   0, "\"&gt;"},
    /*  98 */ {       " ", identity,       0, "='"},
    /*  99 */ {        "", uppercasefirst, 0, ","},
    /* 100 */ {        "", identity,       0, "ize "},
    /* 101 */ {        "", uppercaseall,   0, "."},
    /* 102 */ {"\xc2\xa0", identity,       0, ""},
    /* 103 */ {       " ", identity,       0, ","},
    /* 104 */ {        "", uppercasefirst, 0, "=\""},
    /* 105 */ {        "", uppercaseall,   0, "=\""},
    /* 106 */ {        "", identity,       0, "ous "},
    /* 107 */ {        "", uppercaseall,   0, ", "},
    /* 108 */ {        "", uppercasefirst, 0, "='"},
    /* 109 */ {       " ", uppercasefirst, 0, ","},
    /* 110 */ {       " ", uppercaseall,   0, "=\""},
    /* 111 */ {       " ", uppercaseall,   0, ", "},
    /* 112 */ {        "", uppercaseall,   0, ","},
    /* 113 */ {        "", uppercaseall,   0, "("},
    /* 114 */ {        "", uppercaseall,   0, ". "},
    /* 115 */ {       " ", uppercaseall,   0, "."},
    /* 116 */ {        "", uppercaseall,   0, "='"},
    /* 117 */ {       " ", uppercaseall,   0, ". "},
    /* 118 */ {       " ", uppercasefirst, 0, "=\""},
    /* 119 */ {       " ", uppercaseall,   0, "='"},
    /* 120 */ {       " ", uppercasefirst, 0, "='"}
};
